### ISSUE TITLE
Standardise treaty text language

### ISSUE THREAD

**Issue by jhollway** [globalgov/manypkgs#17]

**Comment by henriquesposito** [comment]
Thank you for the feedback, I will take a look at this issue tomorrow!

**Comment by henriquesposito** [comment]
There is still as issue with the NULL returns from that appear connected to the Google translate (and API keys)...

This appears to be an issue for the current version of standardise_titles() on the main branch of qCreate as well, which was working and was used to standardize titles in qEnviron.

@EstherPeev could you try, if you have time today, to use/modify standadise_titles() with a microsoft API key instead of google? Let me know how it goes if so.
