### ISSUE TITLE
Define a consistent way of dealing with coding errors across many universe packages

### ISSUE THREAD

**Issue by BBieri** [globalgov/manypkgs#78]
Following a chat with @henriquesposito, we realized that there are different approaches across many-packages when dealing with coding errors. `{manyenviron}` deals with these in the preparation scripts while `{manystates}` corrects them in a separate "gnevar" script (e.g. Archigos and ArchigosGnevar).

We should think about standardizing these approaches across data packages to avoid going in different directions and having high switching costs down the line.

Here are the two solutions, we have thought about with @henriquesposito :

## Deal with coding errors in the original data preparation script:

The benefit of this solution is that we will have a clearer file structure within data packages and that it will be easier to assemble data. The main drawback is that we might end up (in extreme cases) altering quite a lot of data making the "processed" dataset far off the original one.

## Deal with coding errors in a *separate* data preparation script

The main advantage of this solution is that we are able to clearly showcase our coding contribution. The main drawback of this method is that we carry over coding errors from the original dataset. This will have consequences on scripts using the data down the line such as `{skimr}` reports failing to parse wrongly coded dates for example.

What do you think @jaeltan @jhollway @henriquesposito ?

**Comment by henriquesposito** [comment]
Thank you for raising this issue @BBieri ! And thank you @jhollway for the clarification.

Then, I think we do need to standardise how this is done across data packages since some corrections are done in some preparation scripts in `{manyenviron}` and `{manytrade}`. For example, there are some "weird" duplicates (code errors) that are removed for some datasets in these packages. As well, as it stands, we necessarily require that contributors standardise dates and titles and rename/recode several variables in the preparation scripts and for the tests we provide, though we keep the same name for these datasets within the database. 

Just to be clear, across all the data packages, we will have the original dataset file (e.g. COW) in the data raw folder, a dataset that is as close to original as possible in the database and that is exported (e.g. states$COW), and also a prepared dataset that corrects for some of these minor mistakes in the same database (states$COW_GNEVAR)?

Please let us know @jhollway if this is the structure you want and we can make sure this is consistent across all the data packages and in regards to tests, instructions, and templates in `{manypkgs}`. Thank you.

Just as a side note, having as close to original datasets exported could create some issues for end-users using `consolidate()`.

**Comment by jhollway** [comment]
Perhaps having e.g. `standardise_dates()` return an NA if there's a particularly ambiguous date means that it's still `consolidate()` compatible, and the `gnevar`/correctly coded version will still take precedence upon consolidation?
