### ISSUE TITLE
Add function to extract dates in words and convert them to messydate format

### ISSUE THREAD

**Issue by jaeltan** [globalgov/manypkgs#79]
Many treaties have their dates of signature written in words (eg. two thousand and nine, May twenty-sixth) instead of YYYY-MM-DD format or other numerical formats. Need to extract these dates and convert them into messydt format to incorporate into datasets.

**Comment by henriquesposito** [comment]
I had a function in '{poldis}` that extract dates from texts. I moved the function to manypkgs for now, since I think I will be removing the function from poldis in the future in any case. I have added a first version of the function to the text_tools script in manypkgs. @jaeltan could you please double check if it works for you and make any necessary changes/improvements? Could you also please add some tests for the function?

@jhollway do you think we should keep this function in manypkgs or possibly move to messydates?

**Comment by jhollway** [comment]
Yes, `{messydates}` may be a good home for it.
