### ISSUE TITLE
translateR dependency has been archived

### ISSUE THREAD

**Issue by BBieri** [globalgov/manypkgs#80]
[translateR](https://CRAN.R-project.org/package=translateR) has been archived a couple of days ago by CRAN. We might need to find an alternative solution if the original maintainer no longer maintains it.

**Comment by jhollway** [comment]
It has been archived because emails to the maintainer were undeliverable. The last time `{translateR}` was released (v1.0) was 2014-07-09. Perhaps it is safer just to back-engineer what we need from this function, recognising where we got the code from, and this should make the package less dependency-reliant.

**Comment by henriquesposito** [comment]
There are several other available functions/package replacements (see googleLanguageR and deeplr). However, I wonder if we should continue to offer this functionality at all since it adds several package dependencies, require users to add an API, and I am not sure many users will actually use it... What do you think @BBieri and @jhollway?

**Comment by BBieri** [comment]
Thanks for your comments @jhollway and @henriquesposito. 

- Regarding @jhollway 's comment: 
> I checked the feasibility of reverse-engineering the `{translateR}` package functions and it will end up adding a lot of dependencies. In my opinion it is not worth the additional dependencies for a functionality that data package contributors can run in their data preparations scripts directly. Hence, I agree with @henriquesposito on that.
 
- Regarding @henriquesposito 's comment:
> I checked whether we could easily replace the function with the two packages you mention within the function and it turns out that the former does not "work out of the box" since the user needs to specify a local JSON file to connect oneself to the API. The issue is a little different for `{deeplr}` which requires the subscription of a "Pro" developer account which costs about 5 EUR a month. This leads me to agree with @henriquesposito too.

Taking this into account, I would let the contributors deal with the automatic translation in their respective data preparation scripts. What do you think?

**Comment by jhollway** [comment]
It looks like a "Pro" `{deeplr}` account is not required -- there is a "Free" version, which however is limited to 500000 characters/month.

**Comment by henriquesposito** [comment]
I updated the `standardise_titles()` function to use the Deepl translation platform. The function now works with the authentication key from the website, there is indeed a free version there. It is also much more intuitive/easier to use than generating google API keys. This has, however. made the `lingua()` function redundant, since we do not need to specify, or find, which language the source texts are from. The `lingua()` function was, therefore, removed.
